telegram:
  token: "YOUR_BOT_TOKEN"
  chat_ids: [123456789, -987654321]

dingtalk:
  webhook_url: "YOUR_WEBHOOK_URL"
  secret: "YOUR_SECRET"

log:
  level: "info"  # 日志级别：debug, info, warn, error
  file_path: "/var/log/tg-forward/main.log"  # 日志文件路径
  max_size: 100  # 单个日志文件最大大小（MB）
  max_files: 7  # 最大保留文件数

queue:
  type: "leveldb"  # 可选: "memory" 或 "leveldb"
  path: "/var/lib/tg-forward"  # LevelDB 存储路径

retry:
  max_attempts: 3  # 最大重试次数
  interval: 60  # 重试间隔（秒）

metrics:
  enabled: true  # 是否启用指标收集
  port: 9090  # 收集间隔（秒）
  output_file: "/var/log/tg-forward/metrics.json"  # 指标输出文件路径

s3:
  endpoint: "YOUR_S3_ENDPOINT"  # 例如：s3.amazonaws.com 或 play.min.io
  region: "YOUR_REGION"  # 例如：us-east-1
  bucket: "YOUR_BUCKET_NAME"
  access_key_id: "YOUR_ACCESS_KEY"
  secret_access_key: "YOUR_SECRET_KEY"
  use_ssl: true
  public_base_url: "YOUR_PUBLIC_URL"  # 例如：https://cdn.example.com 