telegram:
  token: "YOUR_BOT_TOKEN"
  chat_ids: [123456789]  # 要监听的群组 ID

dingtalk:
  webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
  secret: "YOUR_SECRET"
  enable_at: true
  at_mobiles: ["13800138000"]
  is_at_all: false
  notify_verbose: true

bark:
  enabled: true
  keys: ["YOUR_BARK_KEY1", "YOUR_BARK_KEY2"]
  sound: "minuet"
  icon: "https://example.com/icon.jpg"

harmony:
  enabled: true
  user_ids: ["mycs1231", "mycs1232"]  # HarmonyOS_MeoW 用户 ID 列表
  base_url: "https://api.chuckfang.com"  # 可选，默认为 https://api.chuckfang.com

s3:
  enabled: true
  endpoint: "YOUR_S3_ENDPOINT"
  bucket: "YOUR_BUCKET"
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  region: "YOUR_REGION"
  use_ssl: true

queue:
  type: "leveldb"  # 可选: memory, leveldb
  path: "/var/lib/tg-forward/queue"

log:
  level: "info"
  file_path: "/var/log/tg-forward/app.log"
  max_size: 100  # MB
  max_files: 10

metrics:
  enabled: true
  interval: 60
  output_file: "/var/lib/tg-forward/metrics.json"
  http:
    enabled: true
    port: 9090
    path: "/metrics"
    auth: true
    api_key: "YOUR_API_KEY"

retry:
  max_attempts: 3  # 最大重试次数
  interval: 60  # 重试间隔（秒）

metrics:
  enabled: true  # 是否启用指标收集
  port: 9090  # 收集间隔（秒）
  output_file: "/var/log/tg-forward/metrics.json"  # 指标输出文件路径

public_base_url: "YOUR_PUBLIC_URL"  # 可选：CDN 或公共访问 URL，例如：https://cdn.example.com 