telegram:
  token: "YOUR_BOT_TOKEN"
  chat_ids: [123456789, -987654321]

dingtalk:
  webhook_url: "YOUR_WEBHOOK_URL"
  secret: "YOUR_SECRET"
  enable_at: false  # 是否启用 @ 功能
  at_mobiles: ["13800138000", "13900139000"]  # 需要 @ 的手机号列表
  is_at_all: false  # 是否 @ 所有人
  notify_verbose: false  # 是否显示详细信息，设为 false 则只显示消息类型提醒

log:
  level: "debug"  # 日志级别：debug, info, warn, error
  file_path: "/var/log/tg-forward/main.log"  # 日志文件路径
  max_size: 100  # 单个日志文件最大大小（MB）
  max_files: 7  # 最大保留文件数

queue:
  type: "leveldb"  # 可选: "memory" 或 "leveldb"
  path: "/var/lib/tg-forward"  # LevelDB 存储路径

retry:
  max_attempts: 3  # 最大重试次数
  interval: 60  # 重试间隔（秒）

metrics:
  enabled: true  # 是否启用指标收集
  port: 9090  # 收集间隔（秒）
  output_file: "/var/log/tg-forward/metrics.json"  # 指标输出文件路径

s3:
  endpoint: "YOUR_S3_ENDPOINT"  # 必填：S3 服务端点，例如：s3.amazonaws.com 或 play.min.io
  region: "YOUR_REGION"  # 必填：S3 区域，例如：us-east-1
  bucket: "YOUR_BUCKET_NAME"  # 必填：存储桶名称
  access_key_id: "YOUR_ACCESS_KEY"  # 必填：访问密钥 ID
  secret_access_key: "YOUR_SECRET_KEY"  # 必填：访问密钥
  use_ssl: true  # 建议启用：使用 SSL 加密传输
  public_base_url: "YOUR_PUBLIC_URL"  # 可选：CDN 或公共访问 URL，例如：https://cdn.example.com 