name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'CHANGELOG.md'
      - 'docs/**'
      - '.github/workflows/pages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd docs
          npm init -y
          npm install marked

      - name: Generate Changelog HTML
        run: |
          cd docs
          node changelog-generator.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true 